### ISSUE TITLE
osx gdx canvas bug

### ISSUE THREAD

**Issue by hendrik-weiler** [rpgboss/rpgboss#274]
If i try on osx to open the animation panel in the database dialog the application runs in an endless loop.

Thats the only error code i could get:

```
info] 10:57:30.749 [AWT-EventQueue-0] INFO  r.e.d.db.AnimationPlayerGdxPanel - Gdx Canvas Constructor
[error] AL lib: (EE) alc_cleanup: 1 device not closed
java.lang.RuntimeException: Nonzero exit code returned from runner: 143
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last editor/compile:run for the full output.
[error] (editor/compile:run) Nonzero exit code returned from runner: 143
[error] Total time: 26 s, completed 14.02.2015 10:57:48
```

**Comment by hscells** [comment]
I am having the same issue - a black box displays in the bottom left corner. Fortunately I am getting stack traces:

```
19:14:21.753 [AWT-EventQueue-0] ERROR rpgboss.editor.RpgDesktop$ - Uncaught exception
java.lang.IllegalStateException: Canvas not yet displayable
	at org.lwjgl.opengl.AWTGLCanvas.makeCurrent(AWTGLCanvas.java:256)
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.makeCurrent(LwjglAWTCanvas.java:421)
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.stop(LwjglAWTCanvas.java:286)
	at rpgboss.editor.uibase.GdxPanel.dispose(GdxPanel.scala:75)
	at rpgboss.editor.dialog.db.AnimationPlayerPanel.dispose(AnimationPlayerPanel.scala:162)
	at rpgboss.editor.dialog.db.AnimationsPanel$$anon$1.dispose(AnimationsPanel.scala:108)
	at rpgboss.editor.uibase.ArrayEditingPanel$$anon$6$$anonfun$onListSelectionChanged$1.apply(ArrayEditingPanel.scala:66)
	at rpgboss.editor.uibase.ArrayEditingPanel$$anon$6$$anonfun$onListSelectionChanged$1.apply(ArrayEditingPanel.scala:66)
	at scala.Option.map(Option.scala:146)
	at rpgboss.editor.uibase.ArrayEditingPanel$$anon$6.onListSelectionChanged(ArrayEditingPanel.scala:66)
	at rpgboss.editor.uibase.ArrayListView$$anonfun$5.applyOrElse(ArrayEditingPanel.scala:29)
	at rpgboss.editor.uibase.ArrayListView$$anonfun$5.applyOrElse(ArrayEditingPanel.scala:28)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.swing.Reactions$Impl$$anonfun$apply$1.apply(Reactions.scala:23)
	at scala.swing.Reactions$Impl$$anonfun$apply$1.apply(Reactions.scala:23)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.swing.Reactions$Impl.apply(Reactions.scala:23)
	at scala.swing.Reactions$Impl.apply(Reactions.scala:17)
	at scala.swing.Publisher$$anonfun$publish$1.apply(Publisher.scala:47)
	at scala.swing.Publisher$$anonfun$publish$1.apply(Publisher.scala:47)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.swing.SingleRefCollection$$anon$4.foreach(Publisher.scala:108)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.swing.RefSet.foreach(Publisher.scala:165)
	at scala.swing.Publisher$class.publish(Publisher.scala:47)
	at scala.swing.ListView$selection$.publish(ListView.scala:180)
	at scala.swing.ListView$selection$$anon$6.valueChanged(ListView.scala:212)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
	at javax.swing.JList.setValueIsAdjusting(JList.java:2140)
	at javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(BasicListUI.java:2796)
	at javax.swing.plaf.basic.BasicListUI$MouseInputHandler.mouseReleased(BasicListUI.java:1526)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at scala.swing.Window.open(Window.scala:66)
	at rpgboss.editor.ProjectPanel$$anon$1$$anon$5$$anonfun$$lessinit$greater$1.apply$mcV$sp(ProjectPanel.scala:67)
	at scala.swing.Action$$anon$2.apply(Action.scala:60)
	at scala.swing.Action$$anon$1.actionPerformed(Action.scala:78)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
19:14:21.791 [AWT-EventQueue-0] DEBUG r.e.d.db.AnimationPlayerGdxPanel - Start
19:14:22.213 [AWT-EventQueue-0] DEBUG r.e.d.db.AnimationPlayerGdxPanel - Destroying GdxPanel
```  

Hopefully this helps!

**Comment by twfrey** [comment]
I am getting a similar situation without the stack trace. Just a black canvas however. If the owner doesn't mind, I pulled the code, and I am going to try finding a way to fix it. However, my skill set doesn't pertain to Java and game development. I focus more on Web Development and C#. I will see what I can do though and reply if I get a fix.
