### ISSUE TITLE
Crash with shops/battles.

### ISSUE THREAD

**Issue by hebriel** [rpgboss/rpgboss#386]
Hey,
When the player have to make a choice, it can't be on the right, because it crashes instantly. Like if I want to go to "Sell" on a shop, the game freezes (but the music is still going sometimes) and I got this error on the terminal 

AL lib: (WW) FreeDevice: (0x7ff1628d1000) Deleting 4 Buffer(s)
Exception in thread "LWJGL Application" java.lang.ArithmeticException: / by zero
	at rpgboss.lib.Utils$.pmod(Utils.scala:136)
	at rpgboss.player.entity.TextChoiceWindow.keyActivate(TextChoiceWindow.scala:155)
	at rpgboss.player.ChoiceInputHandler$class.keyDown(InputMultiplexer.scala:104)
	at rpgboss.player.entity.ChoiceWindow.keyDown(ChoiceWindow.scala:31)
	at rpgboss.player.InputMultiplexer$$anonfun$myKeyDown$1.apply(InputMultiplexer.scala:162)
	at rpgboss.player.InputMultiplexer$$anonfun$myKeyDown$1.apply(InputMultiplexer.scala:162)
	at scala.Option.map(Option.scala:146)
	at rpgboss.player.InputMultiplexer.myKeyDown(InputMultiplexer.scala:162)
	at rpgboss.player.InputMultiplexer$$anonfun$keyDown$1.apply$mcZI$sp(InputMultiplexer.scala:152)
	at rpgboss.player.InputMultiplexer$$anonfun$keyDown$1.apply(InputMultiplexer.scala:152)
	at rpgboss.player.InputMultiplexer$$anonfun$keyDown$1.apply(InputMultiplexer.scala:152)
	at scala.Option.map(Option.scala:146)
	at rpgboss.player.InputMultiplexer.keyDown(InputMultiplexer.scala:152)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:286)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

I don't know why it tries to make a division by 0.
It's the same on battles (Items...) but not on Text/Name board, where it's ok.
Bug ? Ways to fix it with the source code ?
Thanks

**Comment by ravedragon** [comment]
can u screen shot the event?
