### ISSUE TITLE
Connection to Asset Server Exceptions

### ISSUE THREAD

**Issue by tommycli** [rpgboss/rpgboss#414]
Exceptions such as below appear while editor is running and logged in:

javax.websocket.DeploymentException: Connection failed.
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket._connect(GrizzlyClientSocket.java:408)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket.access$000(GrizzlyClientSocket.java:103)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$1.call(GrizzlyClientSocket.java:228)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$1.call(GrizzlyClientSocket.java:224)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket.connect(GrizzlyClientSocket.java:242)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientContainer.openClientSocket(GrizzlyClientContainer.java:95)
	at org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:626)
	at org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:673)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:826)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:110)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:496)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:348)
	at rpgboss.editor.AssetServerConnection$$anon$3.run(AssetServerConnection.scala:142)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException
	at org.glassfish.grizzly.impl.SafeFutureImpl$Sync.innerGet(SafeFutureImpl.java:357)
	at org.glassfish.grizzly.impl.SafeFutureImpl.get(SafeFutureImpl.java:264)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket._connect(GrizzlyClientSocket.java:370)
	... 15 more

**Comment by hendrik-weiler** [comment]
Its possible the host when you logged in is incorrect.

"ws://"+host+":8080/" <-- Thats where the editors is trying to connect to

The host is the hostname where you try to log you in.
The cooperation server should run on assets.rpgboss.com:8080
