### ISSUE TITLE
MidiSequencer Error

### ISSUE THREAD

**Issue by AntumDeluge** [rpgboss/rpgboss#509]
I think I am missing a library on my system (Linux/Lubuntu x86) but I'm not sure which. It appears, from the error, that the Midi Sequencer is not starting:
```
15:37:58.906 [LWJGL Application] ERROR r.model.resource.MidiMusicPlayer - Could not initialize MIDI sequencer: Can not open line
Exception in thread "LWJGL Application" scala.MatchError: null
	at rpgboss.model.resource.MidiMusicPlayer.<init>(Music.scala:68)
	at rpgboss.model.resource.Music.newPlayer(Music.scala:36)
	at rpgboss.player.RpgScreen$$anonfun$playMusic$2.apply(RpgScreen.scala:86)
	at rpgboss.player.RpgScreen$$anonfun$playMusic$2.apply(RpgScreen.scala:84)
	at scala.Option.map(Option.scala:146)
	at rpgboss.player.RpgScreen$class.playMusic(RpgScreen.scala:84)
	at rpgboss.player.StartScreen.playMusic(StartScreen.scala:3)
	at rpgboss.player.ScriptInterface$$anonfun$playMusic$1.apply$mcV$sp(ScriptInterface.scala:354)
	at rpgboss.player.ScriptInterface$$anonfun$playMusic$1.apply(ScriptInterface.scala:354)
	at rpgboss.player.ScriptInterface$$anonfun$playMusic$1.apply(ScriptInterface.scala:354)
	at rpgboss.player.ScriptInterface.rpgboss$player$ScriptInterface$$f$1(ScriptInterface.scala:127)
	at rpgboss.player.ScriptInterface$$anonfun$syncRun$1.apply(ScriptInterface.scala:136)
	at rpgboss.lib.GdxUtils$$anon$1.run(GdxUtils.scala:20)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:250)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:203)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:123)
```

**Comment by AntumDeluge** [comment]
FIXED: The problem was not related to RPGBoss. I just needed to have PulseAudio installed.

For Debian/Ubuntu users:
```# apt install pulseaudio```
