### ISSUE TITLE
Error When Starting Game

### ISSUE THREAD

**Issue by AntumDeluge** [rpgboss/rpgboss#511]
After pressing "New Game", the screen goes black & freezes. The title music continues to play but the game never starts. I believe this error has to do with a tileset that I added:
```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 3
	at rpgboss.player.MapAndAssets$$anonfun$5$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(MapAndAssets.scala:127)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at rpgboss.player.MapAndAssets$$anonfun$5$$anonfun$apply$1.apply$mcVI$sp(MapAndAssets.scala:110)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at rpgboss.player.MapAndAssets$$anonfun$5.apply(MapAndAssets.scala:107)
	at rpgboss.player.MapAndAssets$$anonfun$5.apply(MapAndAssets.scala:105)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at rpgboss.player.MapAndAssets.<init>(MapAndAssets.scala:105)
	at rpgboss.player.MapScreen.setPlayerLoc(MapScreen.scala:95)
	at rpgboss.player.RpgGame.setPlayerLoc(RpgGame.scala:221)
	at rpgboss.player.RpgGame.startNewGame(RpgGame.scala:159)
	at rpgboss.player.ScriptInterface$$anonfun$startNewGame$1.apply(ScriptInterface.scala:996)
	at rpgboss.player.ScriptInterface.rpgboss$player$ScriptInterface$$f$1(ScriptInterface.scala:127)
	at rpgboss.player.ScriptInterface$$anonfun$syncRun$1.apply(ScriptInterface.scala:136)
	at rpgboss.lib.GdxUtils$$anon$1.run(GdxUtils.scala:20)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:250)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:203)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:123)
```

**Comment by AntumDeluge** [comment]
I haven't been able to reproduce the error after modifying maps & tilesets.

**-- Edit --**
So it appears that my problem was related to incompatible images.
