### ISSUE TITLE
Play botton

### ISSUE THREAD

**Issue by fermin423** [rpgboss/rpgboss#512]
Good, when I hit play on windows 10 I will not run the game.

**Comment by AntumDeluge** [comment]
I'm not sure how you could get error output on Windows. On my Linux computer I can run RPGBoss from a terminal & it will output any error traceback when I run the game (see #511).

Often when I run into errors, it is caused by an incompatible image that I have imported. If you have added any custom spritesheets, tilesets, or backgrounds, perhaps you could try removing them & see if the problem persists.

**Comment by fermin423** [comment]
Hi, this is the fault of the game someone save as it is fixed

Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:253)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:289)
        ... 3 more

**Comment by AntumDeluge** [comment]
Looks like an incompatible image. Not sure exactly what it means by "pixel format". RPGBoss seems to be picky about images that can be used. If you figure out which image is causing the problem you could try opening it with an image editor, like [GIMP](https://www.gimp.org/), & exporting it to a new file.
