### ISSUE TITLE
OS X - Program won't start - Terminal runs but Java doesn't.

### ISSUE THREAD

**Issue by rxa081** [rpgboss/rpgboss#514]
I'm on a Mac using the Linux/OSX download provided.

I was designing a game within the program. I imported a custom image which I set to the new title screen image. I saved the game and exited.

Now when I try to start the game, terminal loads up but it never gives me the [Process completed] cue, and the actual program never loads up. I deleted the custom image in case that was the issue and even uninstalled the program and reinstalled it along with Java, and still nothing.

Any suggestions?

**Comment by rxa081** [comment]
This is the code I get in Terminal:

Last login: Wed Oct 25 21:20:10 on ttys001
rafaels-mbp:~ Rafa$ /Users/Rafa/Downloads/rpgboss-0.9.8/rpgboss ; exit;
21:20:35.228 [AWT-EventQueue-0] DEBUG rpgboss.editor.Internationalized$ - Current locale: en_US
21:20:36.954 [AWT-EventQueue-0] ERROR rpgboss.editor.RpgDesktop$ - Uncaught exception
java.lang.StringIndexOutOfBoundsException: begin 0, end 47, length 31
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at rpgboss.model.ProjectData$$anonfun$read$1$$anonfun$fixMp3Filename$1$1.apply(ProjectData.scala:142)
	at rpgboss.model.ProjectData$$anonfun$read$1$$anonfun$fixMp3Filename$1$1.apply(ProjectData.scala:139)
	at scala.Option.foreach(Option.scala:257)
	at rpgboss.model.ProjectData$$anonfun$read$1.fixMp3Filename$1(ProjectData.scala:139)
	at rpgboss.model.ProjectData$$anonfun$read$1.apply(ProjectData.scala:149)
	at rpgboss.model.ProjectData$$anonfun$read$1.apply(ProjectData.scala:133)
	at scala.Option.foreach(Option.scala:257)
	at rpgboss.model.ProjectData$.read(ProjectData.scala:133)
	at rpgboss.model.Project$.readFromDisk(Project.scala:22)
	at rpgboss.editor.MainPanel$$anonfun$9.apply(MainPanel.scala:84)
	at rpgboss.editor.MainPanel$$anonfun$9.apply(MainPanel.scala:81)
	at scala.Option.map(Option.scala:146)
	at rpgboss.editor.MainPanel.<init>(MainPanel.scala:81)
	at rpgboss.editor.RpgDesktop$$anon$1.<init>(RpgDesktop.scala:25)
	at rpgboss.editor.RpgDesktop$.top(RpgDesktop.scala:16)
	at rpgboss.editor.RpgDesktop$.startup(RpgDesktop.scala:60)
	at scala.swing.SwingApplication$$anonfun$main$1.apply$mcV$sp(SwingApplication.scala:7)
	at scala.swing.Swing$$anon$10.run(Swing.scala:34)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by AntumDeluge** [comment]
You can still run the RPGBoss editor, correct? It's your game that won't run?

Did you add any other custom images or audio files? The error output mentions MP3 quite a bit. I wonder if an incompatible audio file isn't to blame. RPGBoss seems to be picky about compatible resources.

**Comment by Leed2822** [comment]
I'm having the same issue right now. Can anyone please help me?
