### ISSUE TITLE
GdxRuntimeException: Page size too small for pixmap

### ISSUE THREAD

**Issue by AntumDeluge** [rpgboss/rpgboss#518]
I'm trying to add the [Mage City Arcanos tileset](https://opengameart.org/node/11192). But whenever I move to a map using the tileset I get the following traceback:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Page size too small for pixmap: tileset/magecity.png
	at com.badlogic.gdx.graphics.g2d.PixmapPacker.pack(PixmapPacker.java:139)
	at rpgboss.player.MapAndAssets$$anonfun$4.apply(MapAndAssets.scala:90)
	at rpgboss.player.MapAndAssets$$anonfun$4.apply(MapAndAssets.scala:87)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at rpgboss.player.MapAndAssets.<init>(MapAndAssets.scala:87)
	at rpgboss.player.MapScreen.setPlayerLoc(MapScreen.scala:95)
	at rpgboss.player.RpgGame.setPlayerLoc(RpgGame.scala:221)
	at rpgboss.player.ScriptInterface$$anonfun$setPlayerLoc$1.apply$mcV$sp(ScriptInterface.scala:165)
	at rpgboss.player.ScriptInterface$$anonfun$setPlayerLoc$1.apply(ScriptInterface.scala:165)
	at rpgboss.player.ScriptInterface$$anonfun$setPlayerLoc$1.apply(ScriptInterface.scala:165)
	at rpgboss.player.ScriptInterface.rpgboss$player$ScriptInterface$$f$1(ScriptInterface.scala:127)
	at rpgboss.player.ScriptInterface$$anonfun$syncRun$1.apply(ScriptInterface.scala:136)
	at rpgboss.lib.GdxUtils$$anon$1.run(GdxUtils.scala:20)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:250)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:203)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:123)
```

I have cropped the tileset to 256x1440 (8 tiles wide by 45 tall) but still have the issue. Is the problem because there is a limit on how many tiles a tileset can have?

**Edit:** That seems to be what the problem is. I split the tileset into two images & now it works.

**Comment by Sandvich** [comment]
This should be closed. I've added a section in the wiki about [asset creation](https://github.com/rpgboss/rpgboss/wiki/5.-Assets) that details the exact size tilemaps should be to avoid this bug.

**Comment by AntumDeluge** [comment]
I think it should still be considered a bug since the engine itself does not give any error output, leaving the user confused as to what the problem could be. The only way to try & figure it out is by running from command line & trying to read cryptic traceback.

**Comment by EgyLynx** [comment]
I think there not limit up/down, but it MUST can divided by 32. (or better it...)
