### ISSUE TITLE
Bug when removing items from the player's inventory

### ISSUE THREAD

**Issue by Sandvich** [rpgboss/rpgboss#528]
Simple setup where the player collects a quest item and then turns it in to an NPC. At the end of the event script I use add/remove item to remove the quest item from their inventory (the event state only triggers if they have the item in their inventory).

Traceback:
`Exception in thread "LWJGL Application" org.mozilla.javascript.WrappedException: Wrapped java.lang.ArrayIndexOutOfBoundsException: 0 (0) >= 1#1)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.Condition__game_countItems_0_____1_39._c_script_0(Condition: game.countItems(0) >= 1:1)
        at org.mozilla.javascript.gen.Condition__game_countItems_0_____1_39.call(Condition: game.countItems(0) >= 1)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen.Condition__game_countItems_0_____1_39.call(Condition: game.countItems(0) >= 1)
        at org.mozilla.javascript.gen.Condition__game_countItems_0_____1_39.exec(Condition: game.countItems(0) >= 1)
        at org.mozilla.javascript.Context.evaluateString(Context.java:1079)
        at rpgboss.model.event.Condition$$anonfun$allConditionsTrue$1.apply(Condition.scala:122)
        at rpgboss.model.event.Condition$$anonfun$allConditionsTrue$1.apply(Condition.scala:120)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at rpgboss.model.event.Condition$.allConditionsTrue(Condition.scala:120)
        at rpgboss.player.entity.EventEntity$$anonfun$updateState$2.apply$mcVI$sp(EventEntity.scala:101)
        at rpgboss.player.entity.EventEntity$$anonfun$updateState$2.apply(EventEntity.scala:99)
        at rpgboss.player.entity.EventEntity$$anonfun$updateState$2.apply(EventEntity.scala:99)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.immutable.Range.foreach(Range.scala:166)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at rpgboss.player.entity.EventEntity.updateState(EventEntity.scala:99)
        at rpgboss.player.entity.EventEntity$$anon$2.notify(EventEntity.scala:78)
        at rpgboss.player.entity.EventEntity$$anon$2.notify(EventEntity.scala:73)
        at scala.collection.mutable.Publisher$$anonfun$publish$1.apply(Publisher.scala:55)
        at scala.collection.mutable.Publisher$$anonfun$publish$1.apply(Publisher.scala:52)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
        at scala.collection.mutable.Publisher$class.publish(Publisher.scala:52)
        at rpgboss.player.PersistentState.publish(PersistentState.scala:28)
        at rpgboss.player.PersistentState.setIntArray(PersistentState.scala:106)
        at rpgboss.player.PersistentState.addRemoveItem(PersistentState.scala:324)
        at rpgboss.player.ScriptInterface$$anonfun$addRemoveItem$1.apply$mcZ$sp(ScriptInterface.scala:766)
        at rpgboss.player.ScriptInterface$$anonfun$addRemoveItem$1.apply(ScriptInterface.scala:766)
        at rpgboss.player.ScriptInterface$$anonfun$addRemoveItem$1.apply(ScriptInterface.scala:766)
        at rpgboss.player.ScriptInterface.rpgboss$player$ScriptInterface$$f$1(ScriptInterface.scala:127)
        at rpgboss.player.ScriptInterface$$anonfun$syncRun$1.apply(ScriptInterface.scala:136)
        at rpgboss.lib.GdxUtils$$anon$1.run(GdxUtils.scala:20)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:250)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:203)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at rpgboss.player.PersistentState.countItems(PersistentState.scala:348)
        at rpgboss.player.ScriptInterface$$anonfun$countItems$1.apply$mcI$sp(ScriptInterface.scala:770)
        at rpgboss.player.ScriptInterface$$anonfun$countItems$1.apply(ScriptInterface.scala:770)
        at rpgboss.player.ScriptInterface$$anonfun$countItems$1.apply(ScriptInterface.scala:770)
        at rpgboss.player.ScriptInterface.rpgboss$player$ScriptInterface$$f$1(ScriptInterface.scala:127)
        at rpgboss.player.ScriptInterface.syncRun(ScriptInterface.scala:134)
        at rpgboss.player.ScriptInterface.countItems(ScriptInterface.scala:769)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        ... 43 more`

Any thoughts on why this is happening?

**Comment by EgyLynx** [comment]
Are you mentioded at if it list a center, it down thinks get unuse... 
I think, is better use at STORY ITEMS at somewhat variable? (but it seeing hardily at inventory :( )
