### ISSUE TITLE
Erro ./gradlew run

### ISSUE THREAD

**Issue by ghost** [rpgboss/rpgboss#557]
deposi que executar o comando 
./gradlew run
um erro com o java acontece

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.4-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.4-all.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
	at org.gradle.wrapper.Download.download(Download.java:45)
	at org.gradle.wrapper.Install$1.call(Install.java:60)
	at org.gradle.wrapper.Install$1.call(Install.java:47)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	... 3 more

Xubuntu 22.04

**Comment by AntumDeluge** [comment]
Edit the file `gradle/wrapper/gradle-wrapper.properties` & change `http` to `https` in the `distributionUrl`.

**Edit:** After doing this, I got some errors about "peer not authenticated". One solution I read about said that certificates needed to be added to the Java environment. ~~But I was able to get around this by opening the project in Android Studio & upgrading gradle. Still not able to build though. Running into some other problems.~~
